name: Auto Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Runs A Signal Command Using The Runner Shell 
    - name: Installing Node
      uses: actions/setup-node@v2-beta
      with:
        version: 12
        
    # Runs A Signal Command Using The Runner Shell 
    - name: Installing Surge
      run: npm install -global surge
    - name: Deploying Using Surge
      run: surge ./ bootcampclass1byrk.surge.sh --token ${{ secrets.SURGE_TOKEN }}
